package com.eveningoutpost.dexdrip.Services.ob1.ble;

public enum GATTConstants {
    DEVICE_NAME(0x2A00,"Device Name"),
    APPEARANCE(0x2A01,"Appearance"),
    PERIPHERAL_PRIVACY_FLAG(0x2A02,"Peripheral Privacy Flag"),
    RECONNECTION_ADDRESS(0x2A03,"Reconnection Address"),
    PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS(0x2A04,"Peripheral Preferred Connection Parameters"),
    SERVICE_CHANGED(0x2A05,"Service Changed"),
    ALERT_LEVEL(0x2A06,"Alert Level"),
    TX_POWER_LEVEL(0x2A07,"Tx Power Level"),
    DATE_TIME(0x2A08,"Date Time"),
    DAY_OF_WEEK(0x2A09,"Day of Week"),
    DAY_DATE_TIME(0x2A0A,"Day Date Time"),
    EXACT_TIME_256(0x2A0C,"Exact Time 256"),
    DST_OFFSET(0x2A0D,"DST_Offset"),
    TIME_ZONE(0x2A0E,"Time Zone"),
    LOCAL_TIME_INFORMATION(0x2A0F,"Local Time Information"),
    TIME_WITH_DST(0x2A11,"Time with DST"),
    TIME_ACCURACY(0x2A12,"Time Accuracy"),
    TIME_SOURCE(0x2A13,"Time Source"),
    REFERENCE_TIME_INFORMATION(0x2A14,"Reference Time Information"),
    TIME_UPDATE_CONTROL_POINT(0x2A16,"Time Update Control Point"),
    TIME_UPDATE_STATE(0x2A17,"Time Update State"),
    GLUCOSE_MEASUREMENT(0x2A18,"Glucose Measurement"),
    BATTERY_LEVEL(0x2A19,"Battery Level"),
    TEMPERATURE_MEASUREMENT(0x2A1C,"Temperature Measurement"),
    TEMPERATURE_TYPE(0x2A1D,"Temperature Type"),
    INTERMEDIATE_TEMPERATURE(0x2A1E,"Intermediate Temperature"),
    MEASUREMENT_INTERVAL(0x2A21,"Measurement Interval"),
    BOOT_KEYBOARD_INPUT_REPORT(0x2A22,"Boot Keyboard Input Report"),
    SYSTEM_ID(0x2A23,"System ID"),
    MODEL_NUMBER_STRING(0x2A24,"Model Number String"),
    SERIAL_NUMBER_STRING(0x2A25,"Serial Number String"),
    FIRMWARE_REVISION_STRING(0x2A26,"Firmware Revision String"),
    HARDWARE_REVISION_STRING(0x2A27,"Hardware Revision String"),
    SOFTWARE_REVISION_STRING(0x2A28,"Software Revision String"),
    MANUFACTURER_NAME_STRING(0x2A29,"Manufacturer Name String"),
    IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST(0x2A2A,"IEEE 11073-20601 Regulatory Certification Data List"),
    CURRENT_TIME(0x2A2B,"Current Time"),
    SCAN_REFRESH(0x2A31,"Scan Refresh"),
    BOOT_KEYBOARD_OUTPUT_REPORT(0x2A32,"Boot Keyboard Output Report"),
    BOOT_MOUSE_INPUT_REPORT(0x2A33,"Boot Mouse Input Report"),
    GLUCOSE_MEASUREMENT_CONTEXT(0x2A34,"Glucose Measurement Context"),
    BLOOD_PRESSURE_MEASUREMENT(0x2A35,"Blood Pressure Measurement"),
    INTERMEDIATE_CUFF_PRESSURE(0x2A36,"Intermediate Cuff Pressure"),
    HEART_RATE_MEASUREMENT(0x2A37,"Heart Rate Measurement"),
    BODY_SENSOR_LOCATION(0x2A38,"Body Sensor Location"),
    HEART_RATE_CONTROL_POINT(0x2A39,"Heart Rate Control Point"),
    ALERT_STATUS(0x2A3F,"Alert Status"),
    RINGER_CONTROL_POINT(0x2A40,"Ringer Control Point"),
    RINGER_SETTING(0x2A41,"Ringer Setting"),
    ALERT_CATEGORY_ID_BIT_MASK(0x2A42,"Alert Category ID_Bit Mask"),
    ALERT_CATEGORY_ID(0x2A43,"Alert Category ID"),
    ALERT_NOTIFICATION_CONTROL_POINT(0x2A44,"Alert Notification Control Point"),
    UNREAD_ALERT_STATUS(0x2A45,"Unread Alert Status"),
    NEW_ALERT(0x2A46,"New Alert"),
    SUPPORTED_NEW_ALERT_CATEGORY(0x2A47,"Supported New Alert Category"),
    SUPPORTED_UNREAD_ALERT_CATEGORY(0x2A48,"Supported Unread Alert Category"),
    BLOOD_PRESSURE_FEATURE(0x2A49,"Blood Pressure Feature"),
    HID_INFORMATION(0x2A4A,"HID_Information"),
    REPORT_MAP(0x2A4B,"Report Map"),
    HID_CONTROL_POINT(0x2A4C,"HID_Control Point"),
    REPORT(0x2A4D,"Report"),
    PROTOCOL_MODE(0x2A4E,"Protocol Mode"),
    SCAN_INTERVAL_WINDOW(0x2A4F,"Scan Interval Window"),
    PNP_ID(0x2A50,"PnP_ID"),
    GLUCOSE_FEATURE(0x2A51,"Glucose Feature"),
    RECORD_ACCESS_CONTROL_POINT(0x2A52,"Record Access Control Point"),
    RSC_MEASUREMENT(0x2A53,"RSC_Measurement"),
    RSC_FEATURE(0x2A54,"RSC_Feature"),
    SC_CONTROL_POINT(0x2A55,"SC_Control Point"),
    AGGREGATE(0x2A5A,"Aggregate"),
    CSC_MEASUREMENT(0x2A5B,"CSC_Measurement"),
    CSC_FEATURE(0x2A5C,"CSC_Feature"),
    SENSOR_LOCATION(0x2A5D,"Sensor Location"),
    PLX_SPOT_CHECK_MEASUREMENT(0x2A5E,"PLX_Spot-Check Measurement"),
    PLX_CONTINUOUS_MEASUREMENT(0x2A5F,"PLX_Continuous Measurement"),
    PLX_FEATURES(0x2A60,"PLX_Features"),
    CYCLING_POWER_MEASUREMENT(0x2A63,"Cycling Power Measurement"),
    CYCLING_POWER_VECTOR(0x2A64,"Cycling Power Vector"),
    CYCLING_POWER_FEATURE(0x2A65,"Cycling Power Feature"),
    CYCLING_POWER_CONTROL_POINT(0x2A66,"Cycling Power Control Point"),
    LOCATION_AND_SPEED(0x2A67,"Location and Speed"),
    NAVIGATION(0x2A68,"Navigation"),
    POSITION_QUALITY(0x2A69,"Position Quality"),
    LN_FEATURE(0x2A6A,"LN_Feature"),
    LN_CONTROL_POINT(0x2A6B,"LN_Control Point"),
    ELEVATION(0x2A6C,"Elevation"),
    PRESSURE(0x2A6D,"Pressure"),
    TEMPERATURE(0x2A6E,"Temperature"),
    HUMIDITY(0x2A6F,"Humidity"),
    TRUE_WIND_SPEED(0x2A70,"True Wind Speed"),
    TRUE_WIND_DIRECTION(0x2A71,"True Wind Direction"),
    APPARENT_WIND_SPEED(0x2A72,"Apparent Wind Speed"),
    APPARENT_WIND_DIRECTION(0x2A73,"Apparent Wind Direction"),
    GUST_FACTOR(0x2A74,"Gust Factor"),
    POLLEN_CONCENTRATION(0x2A75,"Pollen Concentration"),
    UV_INDEX(0x2A76,"UV_Index"),
    IRRADIANCE(0x2A77,"Irradiance"),
    RAINFALL(0x2A78,"Rainfall"),
    WIND_CHILL(0x2A79,"Wind Chill"),
    HEAT_INDEX(0x2A7A,"Heat Index"),
    DEW_POINT(0x2A7B,"Dew Point"),
    DESCRIPTOR_VALUE_CHANGED(0x2A7D,"Descriptor Value Changed"),
    AEROBIC_HEART_RATE_LOWER_LIMIT(0x2A7E,"Aerobic Heart Rate Lower Limit"),
    AEROBIC_THRESHOLD(0x2A7F,"Aerobic Threshold"),
    AGE(0x2A80,"Age"),
    ANAEROBIC_HEART_RATE_LOWER_LIMIT(0x2A81,"Anaerobic Heart Rate Lower Limit"),
    ANAEROBIC_HEART_RATE_UPPER_LIMIT(0x2A82,"Anaerobic Heart Rate Upper Limit"),
    ANAEROBIC_THRESHOLD(0x2A83,"Anaerobic Threshold"),
    AEROBIC_HEART_RATE_UPPER_LIMIT(0x2A84,"Aerobic Heart Rate Upper Limit"),
    DATE_OF_BIRTH(0x2A85,"Date of Birth"),
    DATE_OF_THRESHOLD_ASSESSMENT(0x2A86,"Date of Threshold Assessment"),
    EMAIL_ADDRESS(0x2A87,"Email Address"),
    FAT_BURN_HEART_RATE_LOWER_LIMIT(0x2A88,"Fat Burn Heart Rate Lower Limit"),
    FAT_BURN_HEART_RATE_UPPER_LIMIT(0x2A89,"Fat Burn Heart Rate Upper Limit"),
    FIRST_NAME(0x2A8A,"First Name"),
    FIVE_ZONE_HEART_RATE_LIMITS(0x2A8B,"Five Zone Heart Rate Limits"),
    GENDER(0x2A8C,"Gender"),
    HEART_RATE_MAX(0x2A8D,"Heart Rate Max"),
    HEIGHT(0x2A8E,"Height"),
    HIP_CIRCUMFERENCE(0x2A8F,"Hip Circumference"),
    LAST_NAME(0x2A90,"Last Name"),
    MAXIMUM_RECOMMENDED_HEART_RATE(0x2A91,"Maximum Recommended Heart Rate"),
    RESTING_HEART_RATE(0x2A92,"Resting Heart Rate"),
    SPORT_TYPE_FOR_AEROBIC_AND_ANAEROBIC_THRESHOLDS(0x2A93,"Sport Type for Aerobic and Anaerobic Thresholds"),
    THREE_ZONE_HEART_RATE_LIMITS(0x2A94,"Three Zone Heart Rate Limits"),
    MESH_PROVISIONING_DATA_OUT(0x2ADC,"Mesh Provisioning Data Out"),
    MESH_PROXY_DATA_IN(0x2ADD,"Mesh Proxy Data In"),
    MESH_PROXY_DATA_OUT(0x2ADE,"Mesh Proxy Data Out"),
    AVERAGE_CURRENT(0x2AE0,"Average Current"),
    AVERAGE_VOLTAGE(0x2AE1,"Average Voltage"),
    BOOLEAN(0x2AE2,"Boolean"),
    CHROMATIC_DISTANCE_FROM_PLANCKIAN(0x2AE3,"Chromatic Distance From Planckian"),
    CHROMATICITY_COORDINATES(0x2AE4,"Chromaticity Coordinates"),
    CHROMATICITY_IN_CCT_AND_DUV_VALUES(0x2AE5,"Chromaticity in CCT_And Duv Values"),
    CHROMATICITY_TOLERANCE(0x2AE6,"Chromaticity Tolerance"),
    CIE_13_3_1995_COLOR_RENDERING_INDEX(0x2AE7,"CIE 13.3-1995 Color Rendering Index"),
    COEFFICIENT(0x2AE8,"Coefficient"),
    CORRELATED_COLOR_TEMPERATURE(0x2AE9,"Correlated Color Temperature"),
    COUNT_16(0x2AEA,"Count 16"),
    COUNT_24(0x2AEB,"Count 24"),
    COUNTRY_CODE(0x2AEC,"Country Code"),
    DATE_UTC(0x2AED,"Date UTC"),
    ELECTRIC_CURRENT(0x2AEE,"Electric Current"),
    ELECTRIC_CURRENT_RANGE(0x2AEF,"Electric Current Range"),
    ELECTRIC_CURRENT_SPECIFICATION(0x2AF0,"Electric Current Specification"),
    ELECTRIC_CURRENT_STATISTICS(0x2AF1,"Electric Current Statistics"),
    ENERGY(0x2AF2,"Energy"),
    ENERGY_IN_A_PERIOD_OF_DAY(0x2AF3,"Energy In A_Period Of Day"),
    EVENT_STATISTICS(0x2AF4,"Event Statistics"),
    FIXED_STRING_16(0x2AF5,"Fixed String 16"),
    FIXED_STRING_24(0x2AF6,"Fixed String 24"),
    FIXED_STRING_36(0x2AF7,"Fixed String 36"),
    FIXED_STRING_8(0x2AF8,"Fixed String 8"),
    GENERIC_LEVEL(0x2AF9,"Generic Level"),
    GLOBAL_TRADE_ITEM_NUMBER(0x2AFA,"Global Trade Item Number"),
    ILLUMINANCE(0x2AFB,"Illuminance"),
    LUMINOUS_EFFICACY(0x2AFC,"Luminous Efficacy"),
    LUMINOUS_ENERGY(0x2AFD,"Luminous Energy"),
    LUMINOUS_EXPOSURE(0x2AFE,"Luminous Exposure"),
    LUMINOUS_FLUX(0x2AFF,"Luminous Flux"),
    LUMINOUS_FLUX_RANGE(0x2B00,"Luminous Flux Range"),
    LUMINOUS_INTENSITY(0x2B01,"Luminous Intensity"),
    MASS_FLOW(0x2B02,"Mass Flow"),
    PERCEIVED_LIGHTNESS(0x2B03,"Perceived Lightness"),
    PERCENTAGE_8(0x2B04,"Percentage 8"),
    POWER(0x2B05,"Power"),
    POWER_SPECIFICATION(0x2B06,"Power Specification"),
    RELATIVE_RUNTIME_IN_A_CURRENT_RANGE(0x2B07,"Relative Runtime In A_Current Range"),
    RELATIVE_RUNTIME_IN_A_GENERIC_LEVEL_RANGE(0x2B08,"Relative Runtime In A_Generic Level Range"),
    RELATIVE_VALUE_IN_A_VOLTAGE_RANGE(0x2B09,"Relative Value In A_Voltage Range"),
    RELATIVE_VALUE_IN_AN_ILLUMINANCE_RANGE(0x2B0A,"Relative Value In An Illuminance Range"),
    RELATIVE_VALUE_IN_A_PERIOD_OF_DAY(0x2B0B,"Relative Value In A_Period Of Day"),
    RELATIVE_VALUE_IN_A_TEMPERATURE_RANGE(0x2B0C,"Relative Value In A_Temperature Range"),
    TEMPERATURE_8(0x2B0D,"Temperature 8"),
    TEMPERATURE_8_IN_A_PERIOD_OF_DAY(0x2B0E,"Temperature 8 In A_Period Of Day"),
    TEMPERATURE_8_STATISTICS(0x2B0F,"Temperature 8 Statistics"),
    TEMPERATURE_RANGE(0x2B10,"Temperature Range"),
    TEMPERATURE_STATISTICS(0x2B11,"Temperature Statistics"),
    TIME_DECIHOUR_8(0x2B12,"Time Decihour 8"),
    TIME_EXPONENTIAL_8(0x2B13,"Time Exponential 8"),
    TIME_HOUR_24(0x2B14,"Time Hour 24"),
    TIME_MILLISECOND_24(0x2B15,"Time Millisecond 24"),
    TIME_SECOND_16(0x2B16,"Time Second 16"),
    TIME_SECOND_8(0x2B17,"Time Second 8"),
    VOLTAGE(0x2B18,"Voltage"),
    VOLTAGE_SPECIFICATION(0x2B19,"Voltage Specification"),
    VOLTAGE_STATISTICS(0x2B1A,"Voltage Statistics"),
    VOLUME_FLOW(0x2B1B,"Volume Flow"),
    CHROMATICITY_COORDINATE(0x2B1C,"Chromaticity Coordinate"),
    RC_FEATURE(0x2B1D,"RC_Feature"),
    RC_SETTINGS(0x2B1E,"RC_Settings"),
    RECONNECTION_CONFIGURATION_CONTROL_POINT(0x2B1F,"Reconnection Configuration Control Point"),
    IDD_STATUS_CHANGED(0x2B20,"IDD_Status Changed"),
    IDD_STATUS(0x2B21,"IDD_Status"),
    IDD_ANNUNCIATION_STATUS(0x2B22,"IDD_Annunciation Status"),
    IDD_FEATURES(0x2B23,"IDD_Features"),
    IDD_STATUS_READER_CONTROL_POINT(0x2B24,"IDD_Status Reader Control Point"),
    IDD_COMMAND_CONTROL_POINT(0x2B25,"IDD_Command Control Point"),
    IDD_COMMAND_DATA(0x2B26,"IDD_Command Data"),
    IDD_RECORD_ACCESS_CONTROL_POINT(0x2B27,"IDD_Record Access Control Point"),
    IDD_HISTORY_DATA(0x2B28,"IDD_History Data"),
    CLIENT_SUPPORTED_FEATURES(0x2B29,"Client Supported Features"),
    DATABASE_HASH(0x2B2A,"Database Hash"),
    BSS_CONTROL_POINT(0x2B2B,"BSS_Control Point"),
    BSS_RESPONSE(0x2B2C,"BSS_Response"),
    EMERGENCY_ID(0x2B2D,"Emergency ID"),
    EMERGENCY_TEXT(0x2B2E,"Emergency Text"),
    ENHANCED_BLOOD_PRESSURE_MEASUREMENT(0x2B34,"Enhanced Blood Pressure Measurement"),
    ENHANCED_INTERMEDIATE_CUFF_PRESSURE(0x2B35,"Enhanced Intermediate Cuff Pressure"),
    BLOOD_PRESSURE_RECORD(0x2B36,"Blood Pressure Record"),
    BR_EDR_HANDOVER_DATA(0x2B38,"BR-EDR_Handover Data"),
    BLUETOOTH_SIG_DATA(0x2B39,"Bluetooth SIG_Data"),
    SERVER_SUPPORTED_FEATURES(0x2B3A,"Server Supported Features"),
    PHYSICAL_ACTIVITY_MONITOR_FEATURES(0x2B3B,"Physical Activity Monitor Features"),
    GENERAL_ACTIVITY_INSTANTANEOUS_DATA(0x2B3C,"General Activity Instantaneous Data"),
    GENERAL_ACTIVITY_SUMMARY_DATA(0x2B3D,"General Activity Summary Data"),
    CARDIORESPIRATORY_ACTIVITY_INSTANTANEOUS_DATA(0x2B3E,"CardioRespiratory Activity Instantaneous Data"),
    CARDIORESPIRATORY_ACTIVITY_SUMMARY_DATA(0x2B3F,"CardioRespiratory Activity Summary Data"),
    STEP_COUNTER_ACTIVITY_SUMMARY_DATA(0x2B40,"Step Counter Activity Summary Data"),
    SLEEP_ACTIVITY_INSTANTANEOUS_DATA(0x2B41,"Sleep Activity Instantaneous Data"),
    SLEEP_ACTIVITY_SUMMARY_DATA(0x2B42,"Sleep Activity Summary Data"),
    PHYSICAL_ACTIVITY_MONITOR_CONTROL_POINT(0x2B43,"Physical Activity Monitor Control Point"),
    CURRENT_SESSION(0x2B44,"Current Session"),
    SESSION(0x2B45,"Session"),
    PREFERRED_UNITS(0x2B46,"Preferred Units"),
    HIGH_RESOLUTION_HEIGHT(0x2B47,"High Resolution Height"),
    MIDDLE_NAME(0x2B48,"Middle Name"),
    STRIDE_LENGTH(0x2B49,"Stride Length"),
    HANDEDNESS(0x2B4A,"Handedness"),
    DEVICE_WEARING_POSITION(0x2B4B,"Device Wearing Position"),
    FOUR_ZONE_HEART_RATE_LIMITS(0x2B4C,"Four Zone Heart Rate Limits"),
    HIGH_INTENSITY_EXERCISE_THRESHOLD(0x2B4D,"High Intensity Exercise Threshold"),
    ACTIVITY_GOAL(0x2B4E,"Activity Goal"),
    SEDENTARY_INTERVAL_NOTIFICATION(0x2B4F,"Sedentary Interval Notification"),
    CALORIC_INTAKE(0x2B50,"Caloric Intake"),
    AUDIO_INPUT_STATE(0x2B77,"Audio Input State"),
    GAIN_SETTINGS_ATTRIBUTE(0x2B78,"Gain Settings Attribute"),
    AUDIO_INPUT_TYPE(0x2B79,"Audio Input Type"),
    AUDIO_INPUT_STATUS(0x2B7A,"Audio Input Status"),
    AUDIO_INPUT_CONTROL_POINT(0x2B7B,"Audio Input Control Point"),
    AUDIO_INPUT_DESCRIPTION(0x2B7C,"Audio Input Description"),
    VOLUME_STATE(0x2B7D,"Volume State"),
    VOLUME_CONTROL_POINT(0x2B7E,"Volume Control Point"),
    VOLUME_FLAGS(0x2B7F,"Volume Flags"),
    OFFSET_STATE(0x2B80,"Offset State"),
    AUDIO_LOCATION(0x2B81,"Audio Location"),
    VOLUME_OFFSET_CONTROL_POINT(0x2B82,"Volume Offset Control Point"),
    AUDIO_OUTPUT_DESCRIPTION(0x2B83,"Audio Output Description"),
    DEVICE_TIME_FEATURE(0x2B8E,"Device Time Feature"),
    DEVICE_TIME_PARAMETERS(0x2B8F,"Device Time Parameters"),
    DEVICE_TIME(0x2B90,"Device Time"),
    DEVICE_TIME_CONTROL_POINT(0x2B91,"Device Time Control Point"),
    TIME_CHANGE_LOG_DATA(0x2B92,"Time Change Log Data");

    short value;
    String description;
    GATTConstants(int v, String desc) {
        this.value = (short)v;
        this.description = desc;
    }

    }
